package org.tsc.model;

public enum RecipientNeed {
    EMPLOYMENT,
    MENTAL_HEALTH_SUPPORT,
    MEDICAL_CARE,
    LIFE_SKILLS,
    ELDERLY,
    SERVICE_CONNECTIONS,
    REENTRY,
    DISABILITY,
    SOCIAL_SECURITY,
    HOUSING_PROGRAM;
}
