package org.tsc.model;

public enum RecipientStatus {

    /**
     * HEALTH STATUS
     */
    RECOVERED,

    /**
     * LEAVE SHELTER
     */
    FOUND_PERMANENT_HOUSING,
    INCARCERATED,
    ENTRUSTED_TO_ASSERTIVE_COMMUNITY,
    PASSED_AWAY,
    LONG_TERM_SUBSTANCE_TREATMENT,
    MOVEMENT,
    EXIT_FOR_RULE_VIOLATIONS,
    CONNECTED_TO_MEDICAL_PROVIDERS,

    /**
     * OTHER ACHIEVEMENTS
     */
    NEWLY_EMPLOYED,
    GED_ATTAINED,
    TRAINING_PROGRAMS,
    BANK_ACCOUNTS_OPENED,
    OTHER_ACHIEVEMENTS;

}
